import {randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {connection} from './jira.mjs';
import {jiraRequest} from './auto-reconcile.mjs';
const directory=new URL('./.runtime/tickets/',import.meta.url),locks=new Set();
function project(c){if(!/^[A-Za-z][A-Za-z0-9_]*$/.test(c.project||''))throw Error('Enter a project key in the Jira connection form.');return encodeURIComponent(c.project);}
export async function metadata(c,type,request=jiraRequest){const base='/issue/createmeta/'+project(c)+'/issuetypes';if(type&&!/^\d+$/.test(type))throw Error('Invalid issue type.');let all=[],start=0;while(true){const data=await request(c,base+(type?'/'+type:'')+'?startAt='+start+'&maxResults=100',null,'GET');const values=data.values||data.fields||data.issueTypes;if(!Array.isArray(values))throw Error('Jira did not return creation metadata.');all.push(...values);start+=values.length;if(data.isLast===true||Number.isFinite(data.total)&&start>=data.total)break;if(!values.length)throw Error('Incomplete Jira metadata.');if(!Number.isFinite(data.total)&&data.isLast!==false)break;}return all;}
function valueFor(field,value,cloud){const schema=field.schema||{};if(field.allowedValues?.length){const values=Array.isArray(value)?value:[value];const chosen=values.map(v=>{const found=field.allowedValues.find(x=>String(x.id??x.value??x.name)===String(v));if(!found)throw Error('Invalid option for '+field.name);return found.id?{id:String(found.id)}:found.value?{value:found.value}:{name:found.name};});return schema.type==='array'?chosen:chosen[0];}if(field.fieldId==='parent'||field.key==='parent')return {key:value};if(schema.type==='user')return cloud?{accountId:value}:{name:value};if(schema.type==='number'){const n=Number(value);if(!Number.isFinite(n))throw Error('Invalid number for '+field.name);return n;}if(schema.type==='array'&&schema.items==='string')return String(value).split(',').map(x=>x.trim()).filter(Boolean);if(schema.type==='string'){if(cloud&&(field.fieldId==='description'||field.key==='description'||schema.custom?.endsWith(':textarea')))return {version:1,type:'doc',content:String(value).split('\n').map(line=>({type:'paragraph',content:line?[{type:'text',text:line}]:[]}))};return String(value);}throw Error('Unsupported field '+field.name+'. Create this issue in Jira.');}
export function buildFields(c,type,meta,values){const fields={project:{key:c.project},issuetype:{id:type}};for(const field of meta){const id=field.fieldId||field.key;if(['project','issuetype'].includes(id))continue;const value=values[id];if(value==null||value===''||Array.isArray(value)&&!value.length){if(field.required&&!field.hasDefaultValue)throw Error(field.name+' is required.');continue;}fields[id]=valueFor(field,value,c.kind==='cloud');}if(!String(fields.summary||'').trim())throw Error('Summary is required.');return fields;}
export async function prepare(c,input,request=jiraRequest){connection(c);const types=await metadata(c,null,request);if(!types.some(t=>String(t.id)===input.type))throw Error('This issue type is not available in the project.');const meta=await metadata(c,input.type,request);const fields=buildFields(c,input.type,meta,input.values||{});let link=null;if(input.link?.key){if(!/^[A-Za-z][A-Za-z0-9_]*-\d+$/.test(input.link.key))throw Error('Invalid linked ticket key.');const data=await request(c,'/issueLinkType',null,'GET');if(!data.issueLinkTypes?.some(t=>t.name===input.link.type))throw Error('Select a valid link type.');await request(c,'/issue/'+encodeURIComponent(input.link.key)+'?fields=summary',null,'GET');link={key:input.link.key,type:input.link.type};}const draft={id:randomUUID(),site:connection(c).site,email:c.email||'',project:c.project,fields,link,state:'prepared',at:new Date().toISOString()};await mkdir(directory,{recursive:true});await writeFile(new URL(draft.id+'.json',directory),JSON.stringify(draft),{flag:'wx'});return {id:draft.id,site:draft.site,project:draft.project,fields,link,type:types.find(t=>String(t.id)===input.type)?.name};}
export async function createTicket(c,id,request=jiraRequest){if(!/^[a-f0-9-]{36}$/.test(id||''))throw Error('Invalid draft ID.');if(locks.has(id))throw Error('Creation is already in progress.');locks.add(id);try{const file=new URL(id+'.json',directory);let draft;try{draft=JSON.parse(await readFile(file,'utf8'));}catch{throw Error('Draft not found. Prepare the ticket again.');}if(draft.site!==connection(c).site||draft.project!==c.project||draft.email!==(c.email||''))throw Error('Connection changed. Prepare the ticket again.');if(draft.state==='created')return draft.result;if(draft.state!=='prepared')throw Error('Previous creation outcome is uncertain. Check Jira before creating another ticket.');draft.state='creating';await writeFile(file,JSON.stringify(draft));try{const result=await request(c,'/issue',{fields:draft.fields});if(!result.key)throw Error('Jira did not return a ticket key.');draft.state='created';draft.result={key:result.key,url:draft.site+'/browse/'+encodeURIComponent(result.key),linkStatus:draft.link?'pending':'none'};await writeFile(file,JSON.stringify(draft));if(draft.link){try{await request(c,'/issueLink',{type:{name:draft.link.type},inwardIssue:{key:result.key},outwardIssue:{key:draft.link.key}});draft.result.linkStatus='linked';}catch{draft.result.linkStatus='failed';draft.result.warning='Ticket created, but the additional link failed. Add that link in Jira; do not recreate the ticket.';}await writeFile(file,JSON.stringify(draft));}return draft.result;}catch(e){if(draft.state!=='created'){draft.state='uncertain';await writeFile(file,JSON.stringify(draft));}throw e;}}finally{locks.delete(id);}}
export async function ticketAction(input){const c=input.connection;if(input.action==='types')return {types:await metadata(c)};if(input.action==='fields')return {fields:await metadata(c,input.type)};if(input.action==='links')return jiraRequest(c,'/issueLinkType',null,'GET');if(input.action==='prepare')return prepare(c,input);if(input.action==='create')return createTicket(c,input.id);throw Error('Unknown ticket action.');}

